services:
  bot:
    build: .
    container_name: translator_404_bot
    restart: always
    env_file:
      - .env
    volumes:
      - _storage:/app/storage
    deploy:
      resources:
        limits:
          cpus: "1.5"   # Limit to 1.5 CPU cores
          memory: "512M"  # Limit memory to 512MB
        reservations:
          cpus: "0.2"   # Reserve at least 0.5 CPU cores
          memory: "128M"  # Reserve at least 128MB
    healthcheck:
      test: pidof python bot.py > /dev/null || exit 1
      start_period: 20s
      timeout: 3s
      interval: 15s
volumes:
  _storage:


